services:
  nodeapp:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/corpus:/app/corpus
    depends_on:
      - vectordb
    env_file:
      - ./backend/.env

  vectordb:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
